### PR TITLE
Bulgarian conversion table (bg_BG) fixes of specific letters.

### PR DESCRIPTION
**Pull request by atanasantonov**
Hello,

First of all thank you for this awesome plugin!

As native Bulgarian I  allow myself to propose some fixes in Bulgarian letters. Reference here: [https://2cyr.com/?7]

Letters Й, Ц and Щ needs fixes.
Letters "I" and "i" are not part of Bulgarian language and are useless.

As note letters below "I" and "i" are part of the old Bulgarian and probably are not used these days.

**2021.05.13 Update: After consultation with #translators at wpbulgaria.slack.com the best option is old letters to stay as is.**

All the best,
Atanas

### CODE REVIEW

**Comment by MrGKanev** [comment]
@atanasantonov if we have to be honest don't we need to remove everything after "Я"? All these characters are part of the [old Bulgarian alfabet](https://en.wikipedia.org/wiki/Bulgarian_alphabet):
					'Ѣ' => 'YE',
					'ѣ' => 'ye',
					'Ѫ' => 'О',
					'ѫ' => 'о',
					'Ѳ' => 'FH',
					'ѳ' => 'fh',
					'Ѵ' => 'YH',
					'ѵ' => 'yh',

**Comment by atanasantonov** [comment]
@MrGKanev Probably yes. As seen from the Wikipedia article you shared the last of them "was used until the orthographic reform of 1945". But maybe they can stay just in case somebody can and want to write in Old Bulgarian. I don't know what is better... I'll talk with the WordPress translators team in Bulgaria.

**Comment by atanasantonov** [comment]
Dear @MrGKanev I've a quick chat in #translators at wpbulgaria.slack.com about the old letters. We've agreed that the best option is old letters to stay as is and if somebody use them to be possible to be converted. A traditional Bulgarian saying is "They don't need bread nor water".

**Comment by kagg-design** [comment]
Thank you for the PR.

We use, however, [ISO9 standard](https://ru.wikipedia.org/wiki/ISO_9#%D0%A2%D0%B0%D0%B1%D0%BB._2._%D0%A2%D1%80%D0%B0%D0%BD%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%BF%D0%BE_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5_%D0%91).

You can modify the table in the admin or by the hook `ctl_table`.

**Comment by atanasantonov** [comment]
Thanks @kagg-design I get it.

**Pull request closed without merging**
